var files_dup =
[
    [ "adminstatwindow.cpp", "adminstatwindow_8cpp.html", null ],
    [ "adminstatwindow.h", "adminstatwindow_8h.html", "adminstatwindow_8h" ],
    [ "adminwindow.cpp", "adminwindow_8cpp.html", null ],
    [ "adminwindow.h", "adminwindow_8h.html", "adminwindow_8h" ],
    [ "authwindow.cpp", "authwindow_8cpp.html", null ],
    [ "authwindow.h", "authwindow_8h.html", "authwindow_8h" ],
    [ "mainwindow.cpp", "mainwindow_8cpp.html", null ],
    [ "mainwindow.h", "mainwindow_8h.html", "mainwindow_8h" ],
    [ "registerwindow.cpp", "registerwindow_8cpp.html", null ],
    [ "registerwindow.h", "registerwindow_8h.html", "registerwindow_8h" ],
    [ "regwindow.cpp", "regwindow_8cpp.html", "regwindow_8cpp" ],
    [ "regwindow.h", "regwindow_8h.html", "regwindow_8h" ],
    [ "statisticwindow.cpp", "statisticwindow_8cpp.html", null ],
    [ "statisticwindow.h", "statisticwindow_8h.html", "statisticwindow_8h" ],
    [ "testwindow1.cpp", "testwindow1_8cpp.html", null ],
    [ "testwindow1.h", "testwindow1_8h.html", "testwindow1_8h" ],
    [ "testwindow2.cpp", "testwindow2_8cpp.html", null ],
    [ "testwindow2.h", "testwindow2_8h.html", "testwindow2_8h" ],
    [ "testwindow3.cpp", "testwindow3_8cpp.html", null ],
    [ "testwindow3.h", "testwindow3_8h.html", "testwindow3_8h" ],
    [ "testwindow4.cpp", "testwindow4_8cpp.html", null ],
    [ "testwindow4.h", "testwindow4_8h.html", "testwindow4_8h" ],
    [ "viewwindow.cpp", "viewwindow_8cpp.html", null ],
    [ "viewwindow.h", "viewwindow_8h.html", "viewwindow_8h" ]
];